export { default as $axios } from './api/axiosInstance'
export { SERVER_URL, TOKEN } from './constants'
export { useOnClickOutside } from './lib/hooks/useOnClickOutside/useOnClickOutside'
export { getServerUrl } from './lib/helpers/getServerUrl'
export { Layout } from './ui/Layout'
export { HomeBanner } from './ui/HomeBanner/HomeBanner'
export { Modal } from './ui/Modal/Modal'
export { Tags } from './ui/Tags/Tags'
export { CheckBoxSlide } from './ui/CheckBoxSlide/CheckBoxSlide'
export { ProductBuy } from './ui/ProductBuy/ProductBuy'
