import type { Metadata } from 'next';
import { Raleway } from 'next/font/google';

import '~/app/styles/index.scss';

const raleway = Raleway({ subsets: ['latin'], variable: '--font-family-raleway' });

export const metadata: Metadata = {
  description: 'Generated by create next app',
  icons: [
    {
      rel: 'icon',
      url: '/favicon.ico'
    }
  ],
  title: 'Farfor delivery'
};

const RootLayout = ({ children }: { children: React.ReactNode }) => {
  return (
    <html className={raleway.variable} lang='en'>
      <body className='app'>{children}</body>
    </html>
  );
};

export default RootLayout;
